//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleVPartners.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string names { get; set; }
        public string lastNames { get; set; }
        public string dni { get; set; }
        public string email { get; set; }
        public string dniType { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
